/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package test.thostmduserapi;

public class CThostFtdcExchangeOrderActionErrorField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcExchangeOrderActionErrorField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcExchangeOrderActionErrorField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thostmdapiJNI.delete_CThostFtdcExchangeOrderActionErrorField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ExchangeID_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_OrderSysID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_InstallID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_OrderLocalID_get(swigCPtr, this);
  }

  public void setActionLocalID(String value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ActionLocalID_set(swigCPtr, this, value);
  }

  public String getActionLocalID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ActionLocalID_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return thostmdapiJNI.CThostFtdcExchangeOrderActionErrorField_ErrorMsg_get(swigCPtr, this);
  }

  public CThostFtdcExchangeOrderActionErrorField() {
    this(thostmdapiJNI.new_CThostFtdcExchangeOrderActionErrorField(), true);
  }

}
