/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package test.thostmduserapi;

public class CThostFtdcCombInstrumentGuardField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcCombInstrumentGuardField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcCombInstrumentGuardField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thostmdapiJNI.delete_CThostFtdcCombInstrumentGuardField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    thostmdapiJNI.CThostFtdcCombInstrumentGuardField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thostmdapiJNI.CThostFtdcCombInstrumentGuardField_BrokerID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    thostmdapiJNI.CThostFtdcCombInstrumentGuardField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return thostmdapiJNI.CThostFtdcCombInstrumentGuardField_InstrumentID_get(swigCPtr, this);
  }

  public void setGuarantRatio(double value) {
    thostmdapiJNI.CThostFtdcCombInstrumentGuardField_GuarantRatio_set(swigCPtr, this, value);
  }

  public double getGuarantRatio() {
    return thostmdapiJNI.CThostFtdcCombInstrumentGuardField_GuarantRatio_get(swigCPtr, this);
  }

  public CThostFtdcCombInstrumentGuardField() {
    this(thostmdapiJNI.new_CThostFtdcCombInstrumentGuardField(), true);
  }

}
