/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package test.thostmduserapi;

public class CThostFtdcLoginInfoField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcLoginInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcLoginInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thostmdapiJNI.delete_CThostFtdcLoginInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrontID(int value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_SessionID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_UserID_get(swigCPtr, this);
  }

  public void setLoginDate(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_LoginDate_set(swigCPtr, this, value);
  }

  public String getLoginDate() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_LoginDate_get(swigCPtr, this);
  }

  public void setLoginTime(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_LoginTime_set(swigCPtr, this, value);
  }

  public String getLoginTime() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_LoginTime_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_IPAddress_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_UserProductInfo_get(swigCPtr, this);
  }

  public void setInterfaceProductInfo(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_InterfaceProductInfo_set(swigCPtr, this, value);
  }

  public String getInterfaceProductInfo() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_InterfaceProductInfo_get(swigCPtr, this);
  }

  public void setProtocolInfo(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_ProtocolInfo_set(swigCPtr, this, value);
  }

  public String getProtocolInfo() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_ProtocolInfo_get(swigCPtr, this);
  }

  public void setSystemName(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_SystemName_set(swigCPtr, this, value);
  }

  public String getSystemName() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_SystemName_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_Password_get(swigCPtr, this);
  }

  public void setMaxOrderRef(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_MaxOrderRef_set(swigCPtr, this, value);
  }

  public String getMaxOrderRef() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_MaxOrderRef_get(swigCPtr, this);
  }

  public void setSHFETime(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_SHFETime_set(swigCPtr, this, value);
  }

  public String getSHFETime() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_SHFETime_get(swigCPtr, this);
  }

  public void setDCETime(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_DCETime_set(swigCPtr, this, value);
  }

  public String getDCETime() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_DCETime_get(swigCPtr, this);
  }

  public void setCZCETime(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_CZCETime_set(swigCPtr, this, value);
  }

  public String getCZCETime() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_CZCETime_get(swigCPtr, this);
  }

  public void setFFEXTime(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_FFEXTime_set(swigCPtr, this, value);
  }

  public String getFFEXTime() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_FFEXTime_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_MacAddress_get(swigCPtr, this);
  }

  public void setOneTimePassword(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_OneTimePassword_set(swigCPtr, this, value);
  }

  public String getOneTimePassword() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_OneTimePassword_get(swigCPtr, this);
  }

  public void setINETime(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_INETime_set(swigCPtr, this, value);
  }

  public String getINETime() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_INETime_get(swigCPtr, this);
  }

  public void setIsQryControl(int value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_IsQryControl_set(swigCPtr, this, value);
  }

  public int getIsQryControl() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_IsQryControl_get(swigCPtr, this);
  }

  public void setLoginRemark(String value) {
    thostmdapiJNI.CThostFtdcLoginInfoField_LoginRemark_set(swigCPtr, this, value);
  }

  public String getLoginRemark() {
    return thostmdapiJNI.CThostFtdcLoginInfoField_LoginRemark_get(swigCPtr, this);
  }

  public CThostFtdcLoginInfoField() {
    this(thostmdapiJNI.new_CThostFtdcLoginInfoField(), true);
  }

}
