/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package test.thostmduserapi;

public class CThostFtdcLinkManField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcLinkManField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcLinkManField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thostmdapiJNI.delete_CThostFtdcLinkManField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return thostmdapiJNI.CThostFtdcLinkManField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return thostmdapiJNI.CThostFtdcLinkManField_InvestorID_get(swigCPtr, this);
  }

  public void setPersonType(char value) {
    thostmdapiJNI.CThostFtdcLinkManField_PersonType_set(swigCPtr, this, value);
  }

  public char getPersonType() {
    return thostmdapiJNI.CThostFtdcLinkManField_PersonType_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    thostmdapiJNI.CThostFtdcLinkManField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return thostmdapiJNI.CThostFtdcLinkManField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return thostmdapiJNI.CThostFtdcLinkManField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setPersonName(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_PersonName_set(swigCPtr, this, value);
  }

  public String getPersonName() {
    return thostmdapiJNI.CThostFtdcLinkManField_PersonName_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return thostmdapiJNI.CThostFtdcLinkManField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return thostmdapiJNI.CThostFtdcLinkManField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return thostmdapiJNI.CThostFtdcLinkManField_ZipCode_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    thostmdapiJNI.CThostFtdcLinkManField_Priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return thostmdapiJNI.CThostFtdcLinkManField_Priority_get(swigCPtr, this);
  }

  public void setUOAZipCode(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_UOAZipCode_set(swigCPtr, this, value);
  }

  public String getUOAZipCode() {
    return thostmdapiJNI.CThostFtdcLinkManField_UOAZipCode_get(swigCPtr, this);
  }

  public void setPersonFullName(String value) {
    thostmdapiJNI.CThostFtdcLinkManField_PersonFullName_set(swigCPtr, this, value);
  }

  public String getPersonFullName() {
    return thostmdapiJNI.CThostFtdcLinkManField_PersonFullName_get(swigCPtr, this);
  }

  public CThostFtdcLinkManField() {
    this(thostmdapiJNI.new_CThostFtdcLinkManField(), true);
  }

}
